name: platform_interface
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  copper_island:
    git:
      url: https://github.com/rizentium/copper.git
      path: packages/copper_island
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
